# Generated by Django 5.2.8 on 2025-11-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagFechaPago', models.DateTimeField(auto_now_add=True)),
                ('pagMonto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagMetodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('NEQUI', 'Nequi'), ('TARJETA', 'Tarjeta'), ('DAVIPLATA', 'Daviplata')], default='EFECTIVO', max_length=10)),
                ('pagEstado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('fkIdParqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueos.parqueo')),
            ],
        ),
    ]
