# Generated by Django 5.2.8 on 2025-11-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espNumero', models.CharField(max_length=25)),
                ('espPiso', models.CharField(max_length=25)),
                ('espTipo', models.CharField(max_length=50)),
                ('espEstado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado'), ('RESERVADO', 'Reservado'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=10)),
                ('fkIdTarifa', models.IntegerField()),
            ],
        ),
    ]
