# Generated by Django 5.2.8 on 2025-11-08 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
        ('tarifas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='fkIdTarifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifas.tarifa'),
        ),
    ]
