# Generated by Django 5.2.8 on 2025-11-08 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueos', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novDescripcion', models.TextField()),
                ('novFechaHora', models.DateTimeField(auto_now_add=True)),
                ('fkIdParqueo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueos.parqueo')),
                ('fkIdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
                ('fkIdVehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculo')),
            ],
        ),
    ]
