# Generated by Django 5.2.8 on 2025-11-08 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehPlaca', models.CharField(max_length=50, unique=True)),
                ('vehTipo', models.CharField(max_length=50)),
                ('vehColor', models.CharField(blank=True, max_length=50, null=True)),
                ('vehMarca', models.CharField(blank=True, max_length=50, null=True)),
                ('vehModelo', models.CharField(blank=True, max_length=50, null=True)),
                ('fkIdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
