# Generated by Django 5.2.8 on 2025-11-08 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuDocumento', models.CharField(max_length=50, unique=True)),
                ('usuNombreCompleto', models.CharField(max_length=255)),
                ('usuCorreo', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuTelefono', models.CharField(blank=True, max_length=50, null=True)),
                ('usuClaveHash', models.CharField(max_length=255)),
                ('usuEstado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8)),
                ('usuFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fkIdRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rol')),
            ],
        ),
    ]
