# Generated by Django 5.2.8 on 2025-11-09 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('usuarios', '0003_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fkIdRol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuClaveHash',
            field=models.CharField(help_text='Contraseña hasheada del usuario', max_length=255, verbose_name='Hash de clave'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuCorreo',
            field=models.EmailField(blank=True, help_text='Correo de contacto', max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuDocumento',
            field=models.CharField(help_text='Documento de identidad del usuario', max_length=50, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuEstado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=8, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuFechaRegistro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuNombreCompleto',
            field=models.CharField(help_text='Nombre y apellido(s) del usuario', max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuTelefono',
            field=models.CharField(blank=True, help_text='Número de teléfono', max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios_usuario',
        ),
    ]
