# Generated by Django 5.2.8 on 2025-11-09 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('usuarios', '0005_alter_usuario_options_alter_usuario_fkidrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fkIdRol',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='roles.rol'),
        ),
    ]
