# Generated by Django 5.2.8 on 2025-11-08 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0002_alter_espacio_fkidtarifa'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parHoraEntrada', models.DateTimeField(auto_now_add=True)),
                ('parHoraSalida', models.DateTimeField(blank=True, null=True)),
                ('fkIdEspacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espacios.espacio')),
                ('fkIdVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.vehiculo')),
            ],
        ),
    ]
