# Generated by Django 5.2.8 on 2025-11-08 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logFechaHora', models.DateTimeField(auto_now_add=True)),
                ('logAccion', models.CharField(blank=True, max_length=100, null=True)),
                ('logTabla', models.CharField(blank=True, max_length=100, null=True)),
                ('logIdRegistro', models.CharField(blank=True, max_length=100, null=True)),
                ('logDescripcion', models.TextField(blank=True, null=True)),
                ('fkIdUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
        ),
    ]
