# Generated by Django 5.2.8 on 2025-11-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desNombre', models.CharField(max_length=100)),
                ('desTipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('VALOR_FIJO', 'Valor fijo')], max_length=15)),
                ('desValor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desDescripcion', models.TextField(blank=True, null=True)),
                ('desCondicion', models.CharField(blank=True, max_length=255, null=True)),
                ('desFechaInicio', models.DateField(blank=True, null=True)),
                ('desFechaFin', models.DateField(blank=True, null=True)),
                ('desActivo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoDescontado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fkIdDescuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descuentos.descuento')),
                ('fkIdPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
    ]
