# Generated by Django 5.2.8 on 2025-11-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0002_alter_espacio_fkidtarifa'),
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resFechaReserva', models.DateField()),
                ('resHoraInicio', models.DateTimeField()),
                ('resEstado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default='RESERVADO', max_length=10)),
                ('fkIdEspacio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='espacios.espacio')),
                ('fkIdVehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculo')),
            ],
        ),
    ]
