# Generated by Django 5.2.8 on 2025-11-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarTipoEspacio', models.CharField(max_length=50)),
                ('tarValorHora', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
